package com.example.trip.models



data class TripDetails(var type: String,var tripName : String,var description :String,var price :String,var address:String,var city : String,var latitude : String,var longitude : String)
{
    object Supplier {
        val tripDetails = mutableListOf<TripDetails>(
            TripDetails("Hotel","The Oberoi","A modern & charming hotel with landscaped garden & water bodies, in the heart of business & shopping district. The entire property reflects the tranquility and energy of the beautiful and modern city of Bengaluru.","15360","# 37 - 39 Mahatma Gandhi Road, Bengaluru 560001 India","Bangalore","12.9735","77.6182"),
            TripDetails("Hotel","Palm Meadows Club","Palm Meadows Resort is spread over 5 acres of lush green - a Corporate Leisure Getaway with state of the art facilities located in close proximity to the IT Corridor and 45 minutes away from the Airport. The Resort, in addition to 78 rooms & suites, houses a 3000 sq ft gymnasium, indoor and outdoor swimming pools, full fledged spa providing various treatments, making it just the place to get back to, away from the bustle of the city. In other words it’s work while you are taking a break at Palm Meadows","8260","# Airport Varthur Road Bangalore Karnataka 560066 India","Bangalore","12.9638","77.7396"),
            TripDetails("Hotel","Radisson","Located in the heart of the city of Bengaluru, Radisson Bengaluru City Center is a stylish hotel, overlooking the tranquil and picturesque Ulsoor Lake. We have 90 elegantly appointed rooms and suites, fitted with state-of-the art technology and all modern conveniences. Most of our premier rooms and suites, also have unparalleled views of Ulsoor lake.","6210","# 2 Gangadhar Chetty Road Ulsoor, Bengaluru 560042 India","Bangalore","12.9763","77.6195"),
            TripDetails("Hotel","The Oberoi","A modern & charming hotel with landscaped garden & water bodies, in the heart of business & shopping district. The entire property reflects the tranquility and energy of the beautiful and modern city of Bengaluru.","15360","# 37 - 39 Mahatma Gandhi Road, Bengaluru 560001 India","Bangalore","12.9735","77.6182"),
            TripDetails("Hotel","Palm Meadows Club","Palm Meadows Resort is spread over 5 acres of lush green - a Corporate Leisure Getaway with state of the art facilities located in close proximity to the IT Corridor and 45 minutes away from the Airport. The Resort, in addition to 78 rooms & suites, houses a 3000 sq ft gymnasium, indoor and outdoor swimming pools, full fledged spa providing various treatments, making it just the place to get back to, away from the bustle of the city. In other words it’s work while you are taking a break at Palm Meadows","8260","# Airport Varthur Road Bangalore Karnataka 560066 India","Bangalore","12.9638","77.7396"),
            TripDetails("Hotel","Radisson","Located in the heart of the city of Bengaluru, Radisson Bengaluru City Center is a stylish hotel, overlooking the tranquil and picturesque Ulsoor Lake. We have 90 elegantly appointed rooms and suites, fitted with state-of-the art technology and all modern conveniences. Most of our premier rooms and suites, also have unparalleled views of Ulsoor lake.","6210","# 2 Gangadhar Chetty Road Ulsoor, Bengaluru 560042 India","Bangalore","12.9763","77.6195"),
            TripDetails("Hotel","The Oberoi","A modern & charming hotel with landscaped garden & water bodies, in the heart of business & shopping district. The entire property reflects the tranquility and energy of the beautiful and modern city of Bengaluru.","15360","# 37 - 39 Mahatma Gandhi Road, Bengaluru 560001 India","Bangalore","12.9735","77.6182"),
            TripDetails("Hotel","Palm Meadows Club","Palm Meadows Resort is spread over 5 acres of lush green - a Corporate Leisure Getaway with state of the art facilities located in close proximity to the IT Corridor and 45 minutes away from the Airport. The Resort, in addition to 78 rooms & suites, houses a 3000 sq ft gymnasium, indoor and outdoor swimming pools, full fledged spa providing various treatments, making it just the place to get back to, away from the bustle of the city. In other words it’s work while you are taking a break at Palm Meadows","8260","# Airport Varthur Road Bangalore Karnataka 560066 India","Bangalore","12.9638","77.7396"),
            TripDetails("Hotel","Radisson","Located in the heart of the city of Bengaluru, Radisson Bengaluru City Center is a stylish hotel, overlooking the tranquil and picturesque Ulsoor Lake. We have 90 elegantly appointed rooms and suites, fitted with state-of-the art technology and all modern conveniences. Most of our premier rooms and suites, also have unparalleled views of Ulsoor lake.","6210","# 2 Gangadhar Chetty Road Ulsoor, Bengaluru 560042 India","Bangalore","12.9763","77.6195"),
            TripDetails("Hotel","The Oberoi","A modern & charming hotel with landscaped garden & water bodies, in the heart of business & shopping district. The entire property reflects the tranquility and energy of the beautiful and modern city of Bengaluru.","15360","# 37 - 39 Mahatma Gandhi Road, Bengaluru 560001 India","Bangalore","12.9735","77.6182"),
            TripDetails("Hotel","Palm Meadows Club","Palm Meadows Resort is spread over 5 acres of lush green - a Corporate Leisure Getaway with state of the art facilities located in close proximity to the IT Corridor and 45 minutes away from the Airport. The Resort, in addition to 78 rooms & suites, houses a 3000 sq ft gymnasium, indoor and outdoor swimming pools, full fledged spa providing various treatments, making it just the place to get back to, away from the bustle of the city. In other words it’s work while you are taking a break at Palm Meadows","8260","# Airport Varthur Road Bangalore Karnataka 560066 India","Bangalore","12.9638","77.7396"),
            TripDetails("Hotel","Radisson","Located in the heart of the city of Bengaluru, Radisson Bengaluru City Center is a stylish hotel, overlooking the tranquil and picturesque Ulsoor Lake. We have 90 elegantly appointed rooms and suites, fitted with state-of-the art technology and all modern conveniences. Most of our premier rooms and suites, also have unparalleled views of Ulsoor lake.","6210","# 2 Gangadhar Chetty Road Ulsoor, Bengaluru 560042 India","Bangalore","12.9763","77.6195"),
            TripDetails("Hotel","The Oberoi","A modern & charming hotel with landscaped garden & water bodies, in the heart of business & shopping district. The entire property reflects the tranquility and energy of the beautiful and modern city of Bengaluru.","15360","# 37 - 39 Mahatma Gandhi Road, Bengaluru 560001 India","Bangalore","12.9735","77.6182"),
            TripDetails("Hotel","Palm Meadows Club","Palm Meadows Resort is spread over 5 acres of lush green - a Corporate Leisure Getaway with state of the art facilities located in close proximity to the IT Corridor and 45 minutes away from the Airport. The Resort, in addition to 78 rooms & suites, houses a 3000 sq ft gymnasium, indoor and outdoor swimming pools, full fledged spa providing various treatments, making it just the place to get back to, away from the bustle of the city. In other words it’s work while you are taking a break at Palm Meadows","8260","# Airport Varthur Road Bangalore Karnataka 560066 India","Bangalore","12.9638","77.7396"),
            TripDetails("Hotel","Radisson","Located in the heart of the city of Bengaluru, Radisson Bengaluru City Center is a stylish hotel, overlooking the tranquil and picturesque Ulsoor Lake. We have 90 elegantly appointed rooms and suites, fitted with state-of-the art technology and all modern conveniences. Most of our premier rooms and suites, also have unparalleled views of Ulsoor lake.","6210","# 2 Gangadhar Chetty Road Ulsoor, Bengaluru 560042 India","Bangalore","12.9763","77.6195"),
            TripDetails("Hotel","The Oberoi","A modern & charming hotel with landscaped garden & water bodies, in the heart of business & shopping district. The entire property reflects the tranquility and energy of the beautiful and modern city of Bengaluru.","15360","# 37 - 39 Mahatma Gandhi Road, Bengaluru 560001 India","Bangalore","12.9735","77.6182"),
            TripDetails("Hotel","Palm Meadows Club","Palm Meadows Resort is spread over 5 acres of lush green - a Corporate Leisure Getaway with state of the art facilities located in close proximity to the IT Corridor and 45 minutes away from the Airport. The Resort, in addition to 78 rooms & suites, houses a 3000 sq ft gymnasium, indoor and outdoor swimming pools, full fledged spa providing various treatments, making it just the place to get back to, away from the bustle of the city. In other words it’s work while you are taking a break at Palm Meadows","8260","# Airport Varthur Road Bangalore Karnataka 560066 India","Bangalore","12.9638","77.7396"),
            TripDetails("Hotel","Radisson","Located in the heart of the city of Bengaluru, Radisson Bengaluru City Center is a stylish hotel, overlooking the tranquil and picturesque Ulsoor Lake. We have 90 elegantly appointed rooms and suites, fitted with state-of-the art technology and all modern conveniences. Most of our premier rooms and suites, also have unparalleled views of Ulsoor lake.","6210","# 2 Gangadhar Chetty Road Ulsoor, Bengaluru 560042 India","Bangalore","12.9763","77.6195"),
            TripDetails("Hotel","The Oberoi","A modern & charming hotel with landscaped garden & water bodies, in the heart of business & shopping district. The entire property reflects the tranquility and energy of the beautiful and modern city of Bengaluru.","15360","# 37 - 39 Mahatma Gandhi Road, Bengaluru 560001 India","Bangalore","12.9735","77.6182"),
            TripDetails("Hotel","Palm Meadows Club","Palm Meadows Resort is spread over 5 acres of lush green - a Corporate Leisure Getaway with state of the art facilities located in close proximity to the IT Corridor and 45 minutes away from the Airport. The Resort, in addition to 78 rooms & suites, houses a 3000 sq ft gymnasium, indoor and outdoor swimming pools, full fledged spa providing various treatments, making it just the place to get back to, away from the bustle of the city. In other words it’s work while you are taking a break at Palm Meadows","8260","# Airport Varthur Road Bangalore Karnataka 560066 India","Bangalore","12.9638","77.7396"),
            TripDetails("Hotel","Radisson","Located in the heart of the city of Bengaluru, Radisson Bengaluru City Center is a stylish hotel, overlooking the tranquil and picturesque Ulsoor Lake. We have 90 elegantly appointed rooms and suites, fitted with state-of-the art technology and all modern conveniences. Most of our premier rooms and suites, also have unparalleled views of Ulsoor lake.","6210","# 2 Gangadhar Chetty Road Ulsoor, Bengaluru 560042 India","Bangalore","12.9763","77.6195"),
            TripDetails("Hotel","The Oberoi","A modern & charming hotel with landscaped garden & water bodies, in the heart of business & shopping district. The entire property reflects the tranquility and energy of the beautiful and modern city of Bengaluru.","15360","# 37 - 39 Mahatma Gandhi Road, Bengaluru 560001 India","Bangalore","12.9735","77.6182"),
            TripDetails("Hotel","Palm Meadows Club","Palm Meadows Resort is spread over 5 acres of lush green - a Corporate Leisure Getaway with state of the art facilities located in close proximity to the IT Corridor and 45 minutes away from the Airport. The Resort, in addition to 78 rooms & suites, houses a 3000 sq ft gymnasium, indoor and outdoor swimming pools, full fledged spa providing various treatments, making it just the place to get back to, away from the bustle of the city. In other words it’s work while you are taking a break at Palm Meadows","8260","# Airport Varthur Road Bangalore Karnataka 560066 India","Bangalore","12.9638","77.7396"),
            TripDetails("Hotel","Radisson","Located in the heart of the city of Bengaluru, Radisson Bengaluru City Center is a stylish hotel, overlooking the tranquil and picturesque Ulsoor Lake. We have 90 elegantly appointed rooms and suites, fitted with state-of-the art technology and all modern conveniences. Most of our premier rooms and suites, also have unparalleled views of Ulsoor lake.","6210","# 2 Gangadhar Chetty Road Ulsoor, Bengaluru 560042 India","Bangalore","12.9763","77.6195"),
            TripDetails("Things to do","Bangalore Palace","An epitome of great architecture and beauty, The Majestic Bangalore Palace preserves in it the spice of old regal opulence. Currently the central attraction in Bangalore, the palace was built in the year 1878. Chamarajendra Wadiyar's British Guardians bought the original property in 1873 from the principal of Bangalore Central High School, Rev, J Garret, from his funds.","0","# Vasanth Nagar, Bengaluru, Karnataka 560052","Bangalore","12.9988","77.5921"),
            TripDetails("Things to do","Cubbon Park","Spread over an area of 300 acres, Cubbon Park in the city of Bangalore is a major sightseeing attraction rich in green foliage. It is a green belt region of the city and is an ideal place for nature lovers and those seeking a calm atmosphere. Having been laid down by Lord Cubbon, the park is named so in his honour. It is home to more than 6,000 trees that support a vibrant ecosystem.","0","# Behind High Court, Ambedkar Veedhi, Bangalore, 560001","Bangalore","12.9763","77.5929"),
            TripDetails("Restaurant","Lalbagh Botanical Garden","Lalbagh Botanical Gardens or Lalbagh is an old botanical garden in Bengaluru, India. Started by Hyder Ali and Tipu Sultan, it was later managed under numerous British Superintendents before Indian Independence. It was responsible for the introduction and propagation of numerous ornamental plants as well as those of economic value. It also served a social function as a park and recreational space, with a central glass house dating from 1890 which was used for flower shows","0","# Lalbagh Road, Wilson Garden, Near BMTC Office, Bengaluru, Karnataka, 560004","Bangalore","12.9507","77.5848"),
            TripDetails("Things to do","Bangalore Palace","An epitome of great architecture and beauty, The Majestic Bangalore Palace preserves in it the spice of old regal opulence. Currently the central attraction in Bangalore, the palace was built in the year 1878. Chamarajendra Wadiyar's British Guardians bought the original property in 1873 from the principal of Bangalore Central High School, Rev, J Garret, from his funds.","0","# Vasanth Nagar, Bengaluru, Karnataka 560052","Bangalore","12.9988","77.5921"),
            TripDetails("Things to do","Cubbon Park","Spread over an area of 300 acres, Cubbon Park in the city of Bangalore is a major sightseeing attraction rich in green foliage. It is a green belt region of the city and is an ideal place for nature lovers and those seeking a calm atmosphere. Having been laid down by Lord Cubbon, the park is named so in his honour. It is home to more than 6,000 trees that support a vibrant ecosystem.","0","# Behind High Court, Ambedkar Veedhi, Bangalore, 560001","Bangalore","12.9763","77.5929"),
            TripDetails("Things to do","Lalbagh Botanical Garden","Lalbagh Botanical Gardens or Lalbagh is an old botanical garden in Bengaluru, India. Started by Hyder Ali and Tipu Sultan, it was later managed under numerous British Superintendents before Indian Independence. It was responsible for the introduction and propagation of numerous ornamental plants as well as those of economic value. It also served a social function as a park and recreational space, with a central glass house dating from 1890 which was used for flower shows","0","# Lalbagh Road, Wilson Garden, Near BMTC Office, Bengaluru, Karnataka, 560004","Bangalore","12.9507","77.5848"),
            TripDetails("Things to do","Bangalore Palace","An epitome of great architecture and beauty, The Majestic Bangalore Palace preserves in it the spice of old regal opulence. Currently the central attraction in Bangalore, the palace was built in the year 1878. Chamarajendra Wadiyar's British Guardians bought the original property in 1873 from the principal of Bangalore Central High School, Rev, J Garret, from his funds.","0","# Vasanth Nagar, Bengaluru, Karnataka 560052","Bangalore","12.9988","77.5921"),
            TripDetails("Things to do","Cubbon Park","Spread over an area of 300 acres, Cubbon Park in the city of Bangalore is a major sightseeing attraction rich in green foliage. It is a green belt region of the city and is an ideal place for nature lovers and those seeking a calm atmosphere. Having been laid down by Lord Cubbon, the park is named so in his honour. It is home to more than 6,000 trees that support a vibrant ecosystem.","0","# Behind High Court, Ambedkar Veedhi, Bangalore, 560001","Bangalore","12.9763","77.5929"),
            TripDetails("Things to do","Lalbagh Botanical Garden","Lalbagh Botanical Gardens or Lalbagh is an old botanical garden in Bengaluru, India. Started by Hyder Ali and Tipu Sultan, it was later managed under numerous British Superintendents before Indian Independence. It was responsible for the introduction and propagation of numerous ornamental plants as well as those of economic value. It also served a social function as a park and recreational space, with a central glass house dating from 1890 which was used for flower shows","0","# Lalbagh Road, Wilson Garden, Near BMTC Office, Bengaluru, Karnataka, 560004","Bangalore","12.9507","77.5848"),
            TripDetails("Things to do","Bangalore Palace","An epitome of great architecture and beauty, The Majestic Bangalore Palace preserves in it the spice of old regal opulence. Currently the central attraction in Bangalore, the palace was built in the year 1878. Chamarajendra Wadiyar's British Guardians bought the original property in 1873 from the principal of Bangalore Central High School, Rev, J Garret, from his funds.","0","# Vasanth Nagar, Bengaluru, Karnataka 560052","Bangalore","12.9988","77.5921"),
            TripDetails("Things to do","Cubbon Park","Spread over an area of 300 acres, Cubbon Park in the city of Bangalore is a major sightseeing attraction rich in green foliage. It is a green belt region of the city and is an ideal place for nature lovers and those seeking a calm atmosphere. Having been laid down by Lord Cubbon, the park is named so in his honour. It is home to more than 6,000 trees that support a vibrant ecosystem.","0","# Behind High Court, Ambedkar Veedhi, Bangalore, 560001","Bangalore","12.9763","77.5929"),
            TripDetails("Things to do","Lalbagh Botanical Garden","Lalbagh Botanical Gardens or Lalbagh is an old botanical garden in Bengaluru, India. Started by Hyder Ali and Tipu Sultan, it was later managed under numerous British Superintendents before Indian Independence. It was responsible for the introduction and propagation of numerous ornamental plants as well as those of economic value. It also served a social function as a park and recreational space, with a central glass house dating from 1890 which was used for flower shows","0","# Lalbagh Road, Wilson Garden, Near BMTC Office, Bengaluru, Karnataka, 560004","Bangalore","12.9507","77.5848")
        )
    }
}
