package com.example.trip.models

import com.example.trip.R


data class TripDetails(var type: String,var tripName : String,var description :String,var price :String,var address:String,var city : String,var latitude : String,var longitude : String,var image : Int,var phone_no : String)
{
    object Supplier {
        val tripDetails = mutableListOf<TripDetails>(
            TripDetails("Hotel","The Oberoi","A modern & charming hotel with landscaped garden & water bodies, in the heart of business & shopping district. The entire property reflects the tranquility and energy of the beautiful and modern city of Bengaluru.","15360","# 37 - 39 Mahatma Gandhi Road, Bengaluru 560001 India","Bangalore","12.9735","77.6182", R.drawable.oberoi,"080 2558 5858"),
            TripDetails("Hotel","Palm Meadows Club","Palm Meadows Resort is spread over 5 acres of lush green - a Corporate Leisure Getaway with state of the art facilities located in close proximity to the IT Corridor and 45 minutes away from the Airport. The Resort, in addition to 78 rooms & suites, houses a 3000 sq ft gymnasium, indoor and outdoor swimming pools, full fledged spa providing various treatments, making it just the place to get back to, away from the bustle of the city. In other words it’s work while you are taking a break at Palm Meadows","8260","# Airport Varthur Road Bangalore Karnataka 560066 India","Bangalore","12.9638","77.7396",R.drawable.palm_meadows_club,"080 4644 4600"),
            TripDetails("Things to do","Lalbagh Botanical Garden","Lalbagh Botanical Gardens or Lalbagh is an old botanical garden in Bengaluru, India. Started by Hyder Ali and Tipu Sultan, it was later managed under numerous British Superintendents before Indian Independence. It was responsible for the introduction and propagation of numerous ornamental plants as well as those of economic value. It also served a social function as a park and recreational space, with a central glass house dating from 1890 which was used for flower shows","0","# Lalbagh Road, Wilson Garden, Near BMTC Office, Bengaluru, Karnataka, 560004","Bangalore","12.9507","77.5848",R.drawable.lalbagh_botanical_garden,"080 2657 0181"),
            TripDetails("Things to do","Bangalore Palace","An epitome of great architecture and beauty, The Majestic Bangalore Palace preserves in it the spice of old regal opulence. Currently the central attraction in Bangalore, the palace was built in the year 1878. Chamarajendra Wadiyar's British Guardians bought the original property in 1873 from the principal of Bangalore Central High School, Rev, J Garret, from his funds.","0","# Vasanth Nagar, Bengaluru, Karnataka 560052","Bangalore","12.9988","77.5921",R.drawable.bangalore_palace,"080 4334 4334"),
            TripDetails("Things to do","Cubbon Park","Spread over an area of 300 acres, Cubbon Park in the city of Bangalore is a major sightseeing attraction rich in green foliage. It is a green belt region of the city and is an ideal place for nature lovers and those seeking a calm atmosphere. Having been laid down by Lord Cubbon, the park is named so in his honour. It is home to more than 6,000 trees that support a vibrant ecosystem.","0","# Behind High Court, Ambedkar Veedhi, Bangalore, 560001","Bangalore","12.9763","77.5929",R.drawable.cubbon_park,""),
            TripDetails("Things to do","Lalbagh Botanical Garden","Lalbagh Botanical Gardens or Lalbagh is an old botanical garden in Bengaluru, India. Started by Hyder Ali and Tipu Sultan, it was later managed under numerous British Superintendents before Indian Independence. It was responsible for the introduction and propagation of numerous ornamental plants as well as those of economic value. It also served a social function as a park and recreational space, with a central glass house dating from 1890 which was used for flower shows","0","# Lalbagh Road, Wilson Garden, Near BMTC Office, Bengaluru, Karnataka, 560004","Bangalore","12.9507","77.5848",R.drawable.lalbagh_botanical_garden,"080 2657 0181"),
            TripDetails("Hotel","Radisson","Located in the heart of the city of Bengaluru, Radisson Bengaluru City Center is a stylish hotel, overlooking the tranquil and picturesque Ulsoor Lake. We have 90 elegantly appointed rooms and suites, fitted with state-of-the art technology and all modern conveniences. Most of our premier rooms and suites, also have unparalleled views of Ulsoor lake.","6210","# 2 Gangadhar Chetty Road Ulsoor, Bengaluru 560042 India","Bangalore","12.9763","77.6195",R.drawable.radisson_bangalore,"080 2558 8550"),
            TripDetails("Hotel","The Oberoi","A modern & charming hotel with landscaped garden & water bodies, in the heart of business & shopping district. The entire property reflects the tranquility and energy of the beautiful and modern city of Bengaluru.","15360","# 37 - 39 Mahatma Gandhi Road, Bengaluru 560001 India","Bangalore","12.9735","77.6182",R.drawable.oberoi,"080 2558 5858"),

            TripDetails("Restaurant","Whitefield Bar and Grill","#1 of 10,862 Restaurants in Bengaluru Steakhouse, Bar, Barbecue, Grill, Wine Bar, Indian,Vegetarian Friendly, Gluten Free Options","0","8th Road Bengaluru Marriott Hotel Whitefield, Bengaluru 560066 India","Bangalore","12.9790","77.7283",R.drawable.whitefield_bar_grill,"090660 32558"),
            TripDetails("Hotel","Palm Meadows Club","Palm Meadows Resort is spread over 5 acres of lush green - a Corporate Leisure Getaway with state of the art facilities located in close proximity to the IT Corridor and 45 minutes away from the Airport. The Resort, in addition to 78 rooms & suites, houses a 3000 sq ft gymnasium, indoor and outdoor swimming pools, full fledged spa providing various treatments, making it just the place to get back to, away from the bustle of the city. In other words it’s work while you are taking a break at Palm Meadows","8260","# Airport Varthur Road Bangalore Karnataka 560066 India","Bangalore","12.9638","77.7396",R.drawable.palm_meadows_club,"080 4644 4600"),
            TripDetails("Hotel","Radisson","Located in the heart of the city of Bengaluru, Radisson Bengaluru City Center is a stylish hotel, overlooking the tranquil and picturesque Ulsoor Lake. We have 90 elegantly appointed rooms and suites, fitted with state-of-the art technology and all modern conveniences. Most of our premier rooms and suites, also have unparalleled views of Ulsoor lake.","6210","# 2 Gangadhar Chetty Road Ulsoor, Bengaluru 560042 India","Bangalore","12.9763","77.6195",R.drawable.radisson_bangalore,"080 2558 8550"),
            TripDetails("Hotel","The Oberoi","A modern & charming hotel with landscaped garden & water bodies, in the heart of business & shopping district. The entire property reflects the tranquility and energy of the beautiful and modern city of Bengaluru.","15360","# 37 - 39 Mahatma Gandhi Road, Bengaluru 560001 India","Bangalore","12.9735","77.6182",R.drawable.oberoi,"080 2558 5858"),
            TripDetails("Hotel","Palm Meadows Club","Palm Meadows Resort is spread over 5 acres of lush green - a Corporate Leisure Getaway with state of the art facilities located in close proximity to the IT Corridor and 45 minutes away from the Airport. The Resort, in addition to 78 rooms & suites, houses a 3000 sq ft gymnasium, indoor and outdoor swimming pools, full fledged spa providing various treatments, making it just the place to get back to, away from the bustle of the city. In other words it’s work while you are taking a break at Palm Meadows","8260","# Airport Varthur Road Bangalore Karnataka 560066 India","Bangalore","12.9638","77.7396",R.drawable.palm_meadows_club,"080 4644 4600"),
            TripDetails("Hotel","Radisson","Located in the heart of the city of Bengaluru, Radisson Bengaluru City Center is a stylish hotel, overlooking the tranquil and picturesque Ulsoor Lake. We have 90 elegantly appointed rooms and suites, fitted with state-of-the art technology and all modern conveniences. Most of our premier rooms and suites, also have unparalleled views of Ulsoor lake.","6210","# 2 Gangadhar Chetty Road Ulsoor, Bengaluru 560042 India","Bangalore","12.9763","77.6195",R.drawable.radisson_bangalore,"080 2558 8550"),
            TripDetails("Hotel","The Oberoi","A modern & charming hotel with landscaped garden & water bodies, in the heart of business & shopping district. The entire property reflects the tranquility and energy of the beautiful and modern city of Bengaluru.","15360","# 37 - 39 Mahatma Gandhi Road, Bengaluru 560001 India","Bangalore","12.9735","77.6182",R.drawable.oberoi,"080 2558 5858"),

            TripDetails("Restaurant","Whitefield Bar and Grill","#1 of 10,862 Restaurants in Bengaluru Steakhouse, Bar, Barbecue, Grill, Wine Bar, Indian,Vegetarian Friendly, Gluten Free Options","0","8th Road Bengaluru Marriott Hotel Whitefield, Bengaluru 560066 India","Bangalore","12.9790","77.7283",R.drawable.whitefield_bar_grill,"090660 32558"),
            TripDetails("Hotel","Palm Meadows Club","Palm Meadows Resort is spread over 5 acres of lush green - a Corporate Leisure Getaway with state of the art facilities located in close proximity to the IT Corridor and 45 minutes away from the Airport. The Resort, in addition to 78 rooms & suites, houses a 3000 sq ft gymnasium, indoor and outdoor swimming pools, full fledged spa providing various treatments, making it just the place to get back to, away from the bustle of the city. In other words it’s work while you are taking a break at Palm Meadows","8260","# Airport Varthur Road Bangalore Karnataka 560066 India","Bangalore","12.9638","77.7396",R.drawable.palm_meadows_club,"080 4644 4600"),
            TripDetails("Hotel","Radisson","Located in the heart of the city of Bengaluru, Radisson Bengaluru City Center is a stylish hotel, overlooking the tranquil and picturesque Ulsoor Lake. We have 90 elegantly appointed rooms and suites, fitted with state-of-the art technology and all modern conveniences. Most of our premier rooms and suites, also have unparalleled views of Ulsoor lake.","6210","# 2 Gangadhar Chetty Road Ulsoor, Bengaluru 560042 India","Bangalore","12.9763","77.6195",R.drawable.radisson_bangalore,"080 2558 8550"),
            TripDetails("Hotel","The Oberoi","A modern & charming hotel with landscaped garden & water bodies, in the heart of business & shopping district. The entire property reflects the tranquility and energy of the beautiful and modern city of Bengaluru.","15360","# 37 - 39 Mahatma Gandhi Road, Bengaluru 560001 India","Bangalore","12.9735","77.6182",R.drawable.oberoi,"080 2558 5858"),
            TripDetails("Hotel","Palm Meadows Club","Palm Meadows Resort is spread over 5 acres of lush green - a Corporate Leisure Getaway with state of the art facilities located in close proximity to the IT Corridor and 45 minutes away from the Airport. The Resort, in addition to 78 rooms & suites, houses a 3000 sq ft gymnasium, indoor and outdoor swimming pools, full fledged spa providing various treatments, making it just the place to get back to, away from the bustle of the city. In other words it’s work while you are taking a break at Palm Meadows","8260","# Airport Varthur Road Bangalore Karnataka 560066 India","Bangalore","12.9638","77.7396",R.drawable.palm_meadows_club,"080 4644 4600"),
            TripDetails("Hotel","Radisson","Located in the heart of the city of Bengaluru, Radisson Bengaluru City Center is a stylish hotel, overlooking the tranquil and picturesque Ulsoor Lake. We have 90 elegantly appointed rooms and suites, fitted with state-of-the art technology and all modern conveniences. Most of our premier rooms and suites, also have unparalleled views of Ulsoor lake.","6210","# 2 Gangadhar Chetty Road Ulsoor, Bengaluru 560042 India","Bangalore","12.9763","77.6195",R.drawable.radisson_bangalore,"080 2558 8550"),

            TripDetails("Hotel","The Oberoi","A modern & charming hotel with landscaped garden & water bodies, in the heart of business & shopping district. The entire property reflects the tranquility and energy of the beautiful and modern city of Bengaluru.","15360","# 37 - 39 Mahatma Gandhi Road, Bengaluru 560001 India","Bangalore","12.9735","77.6182",R.drawable.oberoi,"080 2558 5858"),
            TripDetails("Hotel","Palm Meadows Club","Palm Meadows Resort is spread over 5 acres of lush green - a Corporate Leisure Getaway with state of the art facilities located in close proximity to the IT Corridor and 45 minutes away from the Airport. The Resort, in addition to 78 rooms & suites, houses a 3000 sq ft gymnasium, indoor and outdoor swimming pools, full fledged spa providing various treatments, making it just the place to get back to, away from the bustle of the city. In other words it’s work while you are taking a break at Palm Meadows","8260","# Airport Varthur Road Bangalore Karnataka 560066 India","Bangalore","12.9638","77.7396",R.drawable.palm_meadows_club,"080 4644 4600"),
            TripDetails("Hotel","Radisson","Located in the heart of the city of Bengaluru, Radisson Bengaluru City Center is a stylish hotel, overlooking the tranquil and picturesque Ulsoor Lake. We have 90 elegantly appointed rooms and suites, fitted with state-of-the art technology and all modern conveniences. Most of our premier rooms and suites, also have unparalleled views of Ulsoor lake.","6210","# 2 Gangadhar Chetty Road Ulsoor, Bengaluru 560042 India","Bangalore","12.9763","77.6195",R.drawable.radisson_bangalore,"080 2558 8550"),
            TripDetails("Hotel","The Oberoi","A modern & charming hotel with landscaped garden & water bodies, in the heart of business & shopping district. The entire property reflects the tranquility and energy of the beautiful and modern city of Bengaluru.","15360","# 37 - 39 Mahatma Gandhi Road, Bengaluru 560001 India","Bangalore","12.9735","77.6182",R.drawable.oberoi,"080 2558 5858"),
            TripDetails("Hotel","Palm Meadows Club","Palm Meadows Resort is spread over 5 acres of lush green - a Corporate Leisure Getaway with state of the art facilities located in close proximity to the IT Corridor and 45 minutes away from the Airport. The Resort, in addition to 78 rooms & suites, houses a 3000 sq ft gymnasium, indoor and outdoor swimming pools, full fledged spa providing various treatments, making it just the place to get back to, away from the bustle of the city. In other words it’s work while you are taking a break at Palm Meadows","8260","# Airport Varthur Road Bangalore Karnataka 560066 India","Bangalore","12.9638","77.7396",R.drawable.palm_meadows_club,"080 4644 4600"),
            TripDetails("Hotel","Radisson","Located in the heart of the city of Bengaluru, Radisson Bengaluru City Center is a stylish hotel, overlooking the tranquil and picturesque Ulsoor Lake. We have 90 elegantly appointed rooms and suites, fitted with state-of-the art technology and all modern conveniences. Most of our premier rooms and suites, also have unparalleled views of Ulsoor lake.","6210","# 2 Gangadhar Chetty Road Ulsoor, Bengaluru 560042 India","Bangalore","12.9763","77.6195",R.drawable.radisson_bangalore,"080 2558 8550"),
            TripDetails("Hotel","The Oberoi","A modern & charming hotel with landscaped garden & water bodies, in the heart of business & shopping district. The entire property reflects the tranquility and energy of the beautiful and modern city of Bengaluru.","15360","# 37 - 39 Mahatma Gandhi Road, Bengaluru 560001 India","Bangalore","12.9735","77.6182",R.drawable.oberoi,"080 2558 5858"),
            TripDetails("Hotel","Palm Meadows Club","Palm Meadows Resort is spread over 5 acres of lush green - a Corporate Leisure Getaway with state of the art facilities located in close proximity to the IT Corridor and 45 minutes away from the Airport. The Resort, in addition to 78 rooms & suites, houses a 3000 sq ft gymnasium, indoor and outdoor swimming pools, full fledged spa providing various treatments, making it just the place to get back to, away from the bustle of the city. In other words it’s work while you are taking a break at Palm Meadows","8260","# Airport Varthur Road Bangalore Karnataka 560066 India","Bangalore","12.9638","77.7396",R.drawable.palm_meadows_club,"080 4644 4600"),
            TripDetails("Hotel","Radisson","Located in the heart of the city of Bengaluru, Radisson Bengaluru City Center is a stylish hotel, overlooking the tranquil and picturesque Ulsoor Lake. We have 90 elegantly appointed rooms and suites, fitted with state-of-the art technology and all modern conveniences. Most of our premier rooms and suites, also have unparalleled views of Ulsoor lake.","6210","# 2 Gangadhar Chetty Road Ulsoor, Bengaluru 560042 India","Bangalore","12.9763","77.6195",R.drawable.radisson_bangalore,"080 2558 8550"),
            TripDetails("Things to do","Bangalore Palace","An epitome of great architecture and beauty, The Majestic Bangalore Palace preserves in it the spice of old regal opulence. Currently the central attraction in Bangalore, the palace was built in the year 1878. Chamarajendra Wadiyar's British Guardians bought the original property in 1873 from the principal of Bangalore Central High School, Rev, J Garret, from his funds.","0","# Vasanth Nagar, Bengaluru, Karnataka 560052","Bangalore","12.9988","77.5921",R.drawable.bangalore_palace,"080 4334 4334"),
            TripDetails("Things to do","Cubbon Park","Spread over an area of 300 acres, Cubbon Park in the city of Bangalore is a major sightseeing attraction rich in green foliage. It is a green belt region of the city and is an ideal place for nature lovers and those seeking a calm atmosphere. Having been laid down by Lord Cubbon, the park is named so in his honour. It is home to more than 6,000 trees that support a vibrant ecosystem.","0","# Behind High Court, Ambedkar Veedhi, Bangalore, 560001","Bangalore","12.9763","77.5929",R.drawable.cubbon_park,""),
            TripDetails("Things to do","Lalbagh Botanical Garden","Lalbagh Botanical Gardens or Lalbagh is an old botanical garden in Bengaluru, India. Started by Hyder Ali and Tipu Sultan, it was later managed under numerous British Superintendents before Indian Independence. It was responsible for the introduction and propagation of numerous ornamental plants as well as those of economic value. It also served a social function as a park and recreational space, with a central glass house dating from 1890 which was used for flower shows","0","# Lalbagh Road, Wilson Garden, Near BMTC Office, Bengaluru, Karnataka, 560004","Bangalore","12.9507","77.5848",R.drawable.lalbagh_botanical_garden,"080 2657 0181"),
            TripDetails("Things to do","Bangalore Palace","An epitome of great architecture and beauty, The Majestic Bangalore Palace preserves in it the spice of old regal opulence. Currently the central attraction in Bangalore, the palace was built in the year 1878. Chamarajendra Wadiyar's British Guardians bought the original property in 1873 from the principal of Bangalore Central High School, Rev, J Garret, from his funds.","0","# Vasanth Nagar, Bengaluru, Karnataka 560052","Bangalore","12.9988","77.5921",R.drawable.bangalore_palace,"080 4334 4334"),
            TripDetails("Things to do","Cubbon Park","Spread over an area of 300 acres, Cubbon Park in the city of Bangalore is a major sightseeing attraction rich in green foliage. It is a green belt region of the city and is an ideal place for nature lovers and those seeking a calm atmosphere. Having been laid down by Lord Cubbon, the park is named so in his honour. It is home to more than 6,000 trees that support a vibrant ecosystem.","0","# Behind High Court, Ambedkar Veedhi, Bangalore, 560001","Bangalore","12.9763","77.5929",R.drawable.cubbon_park,""),
            TripDetails("Things to do","Bangalore Palace","An epitome of great architecture and beauty, The Majestic Bangalore Palace preserves in it the spice of old regal opulence. Currently the central attraction in Bangalore, the palace was built in the year 1878. Chamarajendra Wadiyar's British Guardians bought the original property in 1873 from the principal of Bangalore Central High School, Rev, J Garret, from his funds.","0","# Vasanth Nagar, Bengaluru, Karnataka 560052","Bangalore","12.9988","77.5921",R.drawable.bangalore_palace,"080 4334 4334"),
            TripDetails("Things to do","Cubbon Park","Spread over an area of 300 acres, Cubbon Park in the city of Bangalore is a major sightseeing attraction rich in green foliage. It is a green belt region of the city and is an ideal place for nature lovers and those seeking a calm atmosphere. Having been laid down by Lord Cubbon, the park is named so in his honour. It is home to more than 6,000 trees that support a vibrant ecosystem.","0","# Behind High Court, Ambedkar Veedhi, Bangalore, 560001","Bangalore","12.9763","77.5929",R.drawable.cubbon_park,""),
            TripDetails("Things to do","Lalbagh Botanical Garden","Lalbagh Botanical Gardens or Lalbagh is an old botanical garden in Bengaluru, India. Started by Hyder Ali and Tipu Sultan, it was later managed under numerous British Superintendents before Indian Independence. It was responsible for the introduction and propagation of numerous ornamental plants as well as those of economic value. It also served a social function as a park and recreational space, with a central glass house dating from 1890 which was used for flower shows","0","# Lalbagh Road, Wilson Garden, Near BMTC Office, Bengaluru, Karnataka, 560004","Bangalore","12.9507","77.5848",R.drawable.lalbagh_botanical_garden,"080 2657 0181"),
            TripDetails("Things to do","Besant Nagar Beach","Elliot's Beach (popularly known as Besant Nagar Beach or Bessie) is located in Besant Nagar, Chennai, India. It forms the end-point of the Marina Beach shore and is named after Edward Elliot, onetime chief magistrate and superintendent of police, Madras.It has the Velankanni Church and the Ashtalakshmi Kovil nearby.In the colonial era, it was a fairly exclusive place limited to white people. As of 2016, there are many restaurants near the beach.There is a police outpost at the beach and the crowd is policed by means of all-terrain vehicles (ATVs) to prevent drowning mishaps. In 2010, there were 11 drowning cases reported off Elliots Beach.In August 2012, the government sanctioned two more all-terrain vehicles for patrolling the beach.","0","6th Avenue, Chennai 600090, India","Chennai","12.9989","80.2719",R.drawable.besant_nagar_beach,""),
            TripDetails("Things to do","Phoenix Market City","Phoenix Market City (Chennai) is a shopping mall developed by Phoenix Mills Limited located in Chennai, Tamil Nadu, India. It was opened in January 2013 and is the second largest mall in the city.","0","142, Velachery main road, Velachery","Chennai","12.9904","80.2171",R.drawable.phoenix,"044 6651 3007"),
            TripDetails("Restaurant","Whitefield Bar and Grill","#1 of 10,862 Restaurants in Bengaluru Steakhouse, Bar, Barbecue, Grill, Wine Bar, Indian,Vegetarian Friendly, Gluten Free Options","0","8th Road Bengaluru Marriott Hotel Whitefield, Bengaluru 560066 India","Bangalore","12.9790","77.7283",R.drawable.whitefield_bar_grill,"090660 32558"),
            TripDetails("Hotel","Savera Hotel","Savera Hotel - Chennai's first ever star hotel is an iconic landmark with a fusion of modernity and tradition, cherished by guests for decades now!","4707","146 Savera Dr Radha Krishnan Salai, Chennai 600004 India","Chennai","13.0460","80.2611",R.drawable.savera,"044 2811 4700"),
            TripDetails("Hotel","GreenPark","For over 25 years, brand GreenPark has stayed true to its fundamental belief – superior service backed by a pragmatic approach to hospitality. With this focus on service quality, we have gained an enviable expertise in blending business with comfort across all our properties. Reason why our guests keep coming back for the GreenPark experience. Explore our properties. We are certain you will agree with our brand of hospitality.From a quick jog before a hearty breakfast to a relaxing foot massage before your journey back home, at GreenPark Chennai, every facility has been thought through to make your stay memorable. Just 12 km from the airport and 15 minutes from the city’s commercial hub, GreenPark Chennai is a hotel few businessmen skip in their itinerary.","6665","Arcot Road Vadapalani, Chennai 600026 India","Chennai","13.0510","80.2084",R.drawable.greenpark,"044 6651 5151"),
            TripDetails("Restaurant","Avartana","\n" +
                    "Avartana exemplifies an exclusive blend of traditional and progressive renditions of Southern Indian cuisine, which is rooted to the gravitas of the unique tastes, aromas and flavours of southern Indian spices.\n" +
                    "The Southern Indian Peninsula is unified by the region’s bounty of pepper and spices. Our offerings forge this unity and encompass a range of specially crafted tasting menus for discerning diners, who may choose to enjoy the pleasures of savouring an array of delicacies crafted by our chefs.\n" +
                    "Pronounced ‘avartan’, the word Avartana means rhythm, iteration, mysticism and magic.\n" +
                    "As the restaurant seeks to represent a new interpretation of South Indian cuisine in contemporary renditions, the name Avartana encapsulates the intention of offering different iterations that revolve around this unique cuisine.\n" +
                    "Presenting Southern Indian cuisine- reinvented and redefined","0","ITC Grand Chola Hotel, Little Mount, Guindy, Chennai, Tamil Nadu 600032","Chennai","13.0105","80.2207",R.drawable.avartana,"044 2220 0000"),
            TripDetails("Restaurant","Barbeque Nation","Barbeque Nation is one of the most successful casual dining restaurant chains in India. Our restaurants are spacious and well appointed with a lot of wood and open-brick wall surfaces to get you in the mood for a nice and relaxing evening with friends, colleagues or family members. The entire cuisine is a happy blend of American, Mediterranean, Oriental and Indian and is available in both vegetarian and non-vegetarian choices. Our unique 'live-grill' - embedded on your table - allow you and your friends to sit around it and experience the warmth of a barbeque party right at your table. You can grill your own starters in a choice of flavours","0"," No. 39, 1st Floor, Star City Serviced Apartment, Bazullah Rd, Near Grand Sweets, T. Nagar, Chennai, Tamil Nadu 600017","Chennai","13.0478","80.2347",R.drawable.barbeque_nation,"044 6480 6060")


        )
    }
}
